name: Generate Static Binary on musl-gcc (Ubuntu)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install musl toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
        shell: bash

      - name: Install ghcup and GHC
        run: |
          curl -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh
          echo ". ~/.ghcup/env" >> ~/.bashrc
          source ~/.ghcup/env
          ghcup install ghc 9.6.7
          ghcup set ghc 9.6.7
          ghcup install cabal 3.10.1.0
          ghcup set cabal 3.10.1.0
        shell: bash

      - name: Clone PMS Repos
        shell: bash
        run: |
          mkdir -p pms bin
          repos=(pty-mcp-server pms-ui-request pms-ui-response pms-ui-notification pms-infrastructure pms-infra-cmdrun pms-infra-procspawn pms-infra-socket pms-infra-watch pms-infra-serial pms-application-service pms-domain-service pms-domain-model)
          for repo in "${repos[@]}"; do
            git clone https://github.com/phoityne/$repo.git pms/$repo
          done

      - name: Set static build flags
        working-directory: pms/pty-mcp-server
        run: |
          echo "package *" > cabal.project.local
          echo "  ghc-options: -optl-static -optl-pthread -optl-Wl,--static -optl-Wl,-no-pie -fno-PIC" >> cabal.project.local
          echo "  cc-options: -static -fno-PIC" >> cabal.project.local
        shell: bash

      - name: Build statically
        working-directory: pms/pty-mcp-server
        env:
          CC: musl-gcc
          LD: musl-gcc
          AR: musl-ar
          RANLIB: musl-ranlib
          CFLAGS: "-static -fno-PIC"
          LDFLAGS: "-static -Wl,--static -Wl,-no-pie"
          PKG_CONFIG_PATH: /usr/lib/musl/pkgconfig:/usr/local/lib/musl/pkgconfig
        shell: bash
        run: |
          ~/.ghcup/bin/cabal update
          ~/.ghcup/bin/cabal configure --disable-shared --enable-static --with-gcc=musl-gcc all
          ~/.ghcup/bin/cabal build all --disable-shared --disable-executable-dynamic
