name: Matrix Build Dispatcher

on:
  workflow_dispatch:

jobs:
  dispatch:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            workflow: .github/workflows/12_build-linux-action.yaml
            job: build-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            workflow: .github/workflows/13_build-mac-action.yaml
            job: build-macos
          - os: windows-latest
            target: x86_64-w64-mingw32
            workflow: .github/workflows/14_build-windows-action.yaml
            job: build-windows

    name: Run ${{ matrix.job }}
    uses: ./.github/workflows/${{ matrix.workflow }}
    with:
      target: ${{ matrix.target }}
    secrets: inherit
