name: Build Linux

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo target
        run: echo "Building for Linux target: ${{ inputs.target }}"
