name: Build macOS

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building for macOS target: ${{ inputs.target }}"
