name: Build Windows

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building for Windows target: ${{ inputs.target }}"
